# craquelure CV fold 3 (val_groups=['KJTHT-SC-L-1RB1-1'])
path: /home/zzz90/research/crack_detection_SepSAM2/sepsam/datasets/crack_cv
train: /home/zzz90/research/crack_detection_SepSAM2/sepsam/datasets/crack_cv/craqfold3/train.txt
val: /home/zzz90/research/crack_detection_SepSAM2/sepsam/datasets/crack_cv/craqfold3/val.txt
nc: 1
names:
  - crack
