# craquelure CV fold 1 (val_groups=['KJTHT-SC-M-2LB1-2'])
path: /home/zzz90/research/crack_detection_SepSAM2/sepsam/datasets/craq_cv
train: /home/zzz90/research/crack_detection_SepSAM2/sepsam/datasets/craq_cv/craqfold1/train.txt
val: /home/zzz90/research/crack_detection_SepSAM2/sepsam/datasets/craq_cv/craqfold1/val.txt
nc: 1
names:
  - craquelure
