# oversampled train (Stage 3) fold 3, median_inst=1060
path: /home/zzz90/research/crack_detection_SepSAM2/sepsam/datasets/heritage_ft_cv
train: /home/zzz90/research/crack_detection_SepSAM2/sepsam/datasets/heritage_ft_cv/fold3/train_oversampled.txt
val: /home/zzz90/research/crack_detection_SepSAM2/sepsam/datasets/heritage_ft_cv/fold3/val.txt
nc: 1
names:
  - crack
